export const dynamic = "force-dynamic"
// Importing the 'Inter' font from Google Fonts
import { Inter } from "next/font/google"
// Importing global styles for the application
import "./globals.css"
// Importing the Navbar component
import Navbar from "@/app/components/NavBarNew"

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"], // Define the character sets to be included (Latin characters)
  display: "swap", // Apply a swap strategy for font loading (to prevent invisible text)
})

// Metadata for the page
export const metadata = {
  title: "Create Next App", // Title of the page
  description: "Generated by create next app", // Description of the app
}

// RootLayout component: This wraps around all the pages
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning={true}>
      {""}
      {/* Applying the Inter font to the entire page */}
      <body>
        <Navbar /> {/* Displaying the Navbar component */}
        {children} {/* Rendering the content of the current page */}
      </body>
    </html>
  )
}
